### PR TITLE
Fix start:mocks and dev:remix

### LINKED ISSUE #20: NPM run dev failing
I keep getting the following when I run 'NPM run dev' and I can't seem to figure out the problem.  Do you have any suggestions? thank you so much 

> dev:css
> npm run generate:css -- --watch

> dev:remix
> node --require ./mocks ./node_modules/.bin/remix dev

🔶 Mock server running
SyntaxError: missing ) after argument list

### PR DESCRIPTION
**Pull request by moishinetzer**
Fixes #20 and #21

### CODE REVIEW

**Comment by moishinetzer** [comment]
@kentcdodds Hi this is awaiting approval to run the workflow, thanks very much!

**Comment by moishinetzer** [comment]
Hmm... So this may have been done preemptively, I can see that this misses out the script files that do some system checks and whatnot... so not so sure if this is just a good temp fix until the scripts can be sorted out or if this just shouldn't be done as it may cause other issues (which I'm sure the script files were created to address)

**Comment by chaance** [comment]
The challenge here is that `cli.js` is really an implementation detail, so I'm not sure we want to hit it directly if we can avoid it. Investigating some other solutions though.

**Comment by kentcdodds** [comment]
I've already got a good solution. I'm working on this now.

**Comment by kentcdodds** [comment]
Could you try the latest version? I'm pretty sure this is resolved now.

**Pull request closed without merging**
