### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
Seems like Cypress is mad 🤔😢

**Comment by mcansh** [comment]
looks like jest dom uses `nullish coalescing` and cypress/webpack isn't a fan

**Comment by machour** [comment]
That nullish coalescing have been in testing dom for a long time.
Maybe try rolling back the cypress upgrade?

**Comment by MichaelDeBoey** [comment]
It seems like the problem is with `@testing-library/dom` `v8.18.0` and above (which is a known problem: https://github.com/testing-library/dom-testing-library/issues/1169), so I pinned it's version (for now)

**Review by machour — APPROVED** [review]

**Comment by dev-xo** [comment]
Thanks you for the PR @MichaelDeBoey, been struggling watching Cypress tests failing, was looking for this!

**Pull request merged**
