### PR TITLE
Add info about .env file in README

### PR DESCRIPTION
**Pull request by Maciekek**
Hello 👋, 
Yesterday I tried to play with this template. I stuck a little with connection to SQLite, because I didn't know that app needs .env file. I am not sure if this information is placed somewhere, so I prepared this README update to save a few minutes of next colleagues ⏰

Hope, you enjoy it✌️

### CODE REVIEW

**Comment by mcansh** [comment]
did you opt out of installing dependencies during "create-remix"? if not, a `.env` file should have been generated for you during "remix init" with the contents of `.env.example` https://github.com/remix-run/indie-stack/blob/main/remix.init/index.js#L65

if you do opt out, you should have seen the following which prompts you to install your dependencies and run "npx remix init"

**Comment by Maciekek** [comment]
I did steps from: https://remix.run/docs/en/v1/tutorials/blog
for me `npm remix init` throw error

image

**Comment by mcansh** [comment]
> I did steps from: [remix.run/docs/en/v1/tutorials/blog](https://remix.run/docs/en/v1/tutorials/blog) for me `npm remix init` throw error
> 
> image

looks like we could be a little safer here when we clean up, can you comment out these lines and re-run it? https://github.com/remix-run/indie-stack/blob/main/remix.init/index.js#L71-L74

**Comment by Maciekek** [comment]
Commented out mentioned lines, got new error:) 
image


image

but .env is generated, so partially it is a success :) 

I don't want to bother you, I managed to work with it differently, so I can live with that. But if you want to check sth with me, I am ready to help :)

**Comment by mcansh** [comment]
hm, do you have a seed file at all in `./prisma`?

**Comment by Maciekek** [comment]
yep, sth is here 
image

didn't change anything in code, just:
- `npx create-remix --template remix-run/indie-stack blog-tutorial` 
- Typescript
- Agreed to do automatically `npm install`
- and then `npx remix init`

**Comment by Maciekek** [comment]
here you can check my whole logs from console from the beginning: 
https://gist.github.com/Maciekek/50730897afdcfeab7d6313b443c94b83

**Comment by mcansh** [comment]
😕☹️ i just ran through the same steps and mine worked - i think the `malloc` error is a memory related error, but you're making it to the end of the npm script 🤪

**Comment by Maciekek** [comment]
image
🤷‍♂️ 

maybe it is just only on my computer, 
Nvm, apart from it, all is good, have a nice day :)

**Pull request closed without merging**
