### PR TITLE
feat: remove `entry.*.ts` files

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
See https://github.com/remix-run/remix/pull/5455

### CODE REVIEW

**Review by mcansh — APPROVED** [review]

**Comment by mcansh** [comment]
we decided earlier that stacks should keep their entry files. https://github.com/remix-run/remix/pull/5455#issue-1584813873

**Comment by MichaelDeBoey** [comment]
Totally forgot about that comment 🙈

Wanted to update the stack, as we also removed these files from our templates & we're updating stacks to have latest updates of them (like `v2_meta` option flag) as well, so it felt/feels a bit weird that we still keep these entry files in our stacks

**Comment by brophdawg11** [comment]
Yeah let's keep the entry files.  We chose to add them back to the templates yesterday due to confusion it was causing.  

This is a different consideration than enabling v2 flags in stacks IMO.  Those are breaking changes in which your app will **not work** in v2 if you don't adopt them so we need to be encouraging folks to use the new APIs.

The optionality of these files is just a small DX convenience - and largely intended for simple demos and such.  I think we're finding from community feedback that _most_ apps need/want these for their own customization so removing from our "production grade" stacks feels like it only adds friction to their path to a produciton-ready app.

**Comment by MichaelDeBoey** [comment]
Superseded by #211

**Pull request closed without merging**
