### PR TITLE
fix: add swapfile

### LINKED ISSUE #200: Fly Instance runs out of memory on deployment
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

- Create an application
- Deploy it to Fly.io
- Do some changes to the DB Schema
- Re-deploy

### Expected Behavior

Migrations are applied and app starts normally

And possibly, prisma shouldn't be installed again with `npx`. It should already be there from dependency installing phase.

### Actual Behavior

Instance runs out of memory while running

`npx prisma migrate deploy`

So the app never starts and it's rolled back.

This is the log from Fly

```
2023-03-13T17:20:18.816 app[ff091a8a] gdl [info] Preparing to run: `sh start.sh` as root

2023-03-13T17:20:18.833 app[ff091a8a] gdl [info] 2023/03/13 17:20:18 listening on [fdaa:1:9e30:a7b:d8:5:ac23:2]:22 (DNS: [fdaa::3]:53)

2023-03-13T17:20:18.837 app[ff091a8a] gdl [info] + npx prisma migrate deploy

2023-03-13T17:20:22.736 app[ff091a8a] gdl [info] npm WARN exec The following package was not found and will be installed: prisma@4.11.0

2023-03-13T17:20:26.836 health[ff091a8a] gdl [error] Health check on port 8080 has failed. Your app is not responding properly. Services exposed on ports [80, 443] will have intermittent failures until the health check passes.

2023-03-13T17:20:27.400 app[ff091a8a] gdl [info] [ 8.678859] Out of memory: Killed process 604 (node) total-vm:11173416kB, anon-rss:124428kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:1444kB oom_score_adj:0
```

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Just like @kwigley's https://github.com/remix-run/blues-stack/pull/183

Fixes #200

### CODE REVIEW

**Review by mcansh — APPROVED** [review]

**Comment by mikeybinns** [comment]
I understand the need for the swapfile, but can this be implemented using the `swap_size_mb` fly.toml option as a cleaner solution than requiring a shell script?
Documented here:
https://fly.io/docs/reference/configuration/#swap_size_mb-option

**Comment by MichaelDeBoey** [comment]
@rubys if that's the case, I guess we can simplify `dockerfile-node` as well?

**Comment by rubys** [comment]
@MichaelDeBoey yes that is correct.  And dockerfile-node already has support for this: https://github.com/fly-apps/dockerfile-node/commit/d489e3a56ab1d30763ae727a32da03a476513c73 ... and if you check the test cases you will see that this already is enabled and tested for indie and blues stacks.

Any chance remix could consider switching to dockerfile node?

**Comment by MichaelDeBoey** [comment]
@rubys if we can support everything that's happening right now in the Dockerfile, I'd be happy to accept a PR that changes docs and CI & removes the current version of Dockerfile, `fly.toml`, ... in both indie-stack & blues-stack

**Comment by rubys** [comment]
I believe we can support everything. If we discover something that needs to be added that can be done quickly, so I'm not worried about that.

The doc changes should be pretty straightforward.  Much of the current README can be replaced by `fly launch`.

The CI will likely take several iterations to get right.  I've already got a test that builds the Dockerfile.  Example: https://github.com/fly-apps/dockerfile-node/actions/runs/5933428308/job/16088842745

If looks like your existing test deploys the app on fly.io.  It doesn't create the application, so it presumes that the app is already present?

So the next step is presumably to figure out what test is needed, subtract out what is already covered, and then write a test for what remains.  Whether that test or tests resides in a remix repository or a fly apps repository doesn't matter to me.

**Comment by MichaelDeBoey** [comment]
@rubys Let's continue the discussion in #252

**Pull request merged**
