### PR TITLE
chore: add npmrc with legacy-peer-deps

### PR DESCRIPTION
**Pull request by mcansh**

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
Do we want this in our templates as well?
Or what's the reason we're including it in our stacks?

**Comment by kentcdodds** [comment]
We had a discussion about this on [discord](https://discord.com/channels/770287896669978684/954545525984722954/1000024948942835712):

image

**Review by kentcdodds — APPROVED** [review]
Looks good 👍

**Review by kentcdodds — APPROVED** [review]
Looks good 👍

**Pull request merged**
